### ISSUE TITLE
1.8 firmware issue

### ISSUE THREAD

**Issue by moelsaied88** [KaufHA/PLF10#1]
Hi! I just purchased a plug and set it up in home assistant and all was working. I then updated the firmware to version 1.8 and now the light on the plug is red, button does nothing, and is disconnected from wifi. I've tried holding down the button to reset, but no luck. Appreciate any guidance.

**Comment by KaufHA** [comment]
Send me an email at brian@kaufha.com and I'll take care of it for you.
