### ISSUE TITLE
Red Led Control not working correctly

### ISSUE THREAD

**Issue by Grafton1046** [KaufHA/PLF10#18]
Upgraded from ESP Home 2023.5.5 to ESP Home 2023.6.1  and noticed that the Red LED control is not working as expected.
have tried each version to 2023.6.4 each is showing the same issue, the Red LED behaves like it's set to Invert power status, if it is set to power status and invert power status.

config yaml:
substitutions:
  name: kauf-plug-7aaa10
packages:
  Kauf.PLF12: github://KaufHA/PLF12/kauf-plf12.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  comment: OilHeaterControl
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

log showing led behavior:

<html><body>

00:02:17 | [D] | [switch:016] | 'Kauf Plug' Turning OFF.    # **red led set to invert power** 
-- | -- | -- | --
00:02:17 | [D] | [switch:066] | 'Kauf Plug': Sending state OFF
00:02:18 | [D] | [switch:066] | 'Kauf Plug Red LED': Sending state ON
00:02:20 | [D] | [switch:012] | 'Kauf Plug' Turning ON.
00:02:20 | [D] | [switch:066] | 'Kauf Plug': Sending state ON
00:02:20 | [D] | [switch:066] | 'Kauf Plug Red LED': Sending state OFF
00:02:20 | [D] | [script:077] | Script 'script_save_changes' restarting (mode: restart)     # **working as expected**
00:02:23 | [D] | [esp8266.preferences:274] | Saving preferences to flash...
00:02:24 | [D] | [select:062] | 'Kauf Plug Red LED Config' - Setting
00:02:24 | [D] | [select:115] | 'Kauf Plug Red LED Config' - Set selected option to: Power Status
00:02:24 | [D] | [select:015] | 'Kauf Plug Red LED Config': Sending state Power Status (index 0) # **changed red led config to power status**
00:02:25 | [D] | [script:077] | Script 'script_save_changes' restarting (mode: restart)
00:02:28 | [D] | [esp8266.preferences:274] | Saving preferences to flash...
00:02:28 | [D] | [switch:016] | 'Kauf Plug' Turning OFF.
00:02:28 | [D] | [switch:066] | 'Kauf Plug': Sending state OFF
00:02:28 | [D] | [switch:066] | 'Kauf Plug Red LED': Sending state ON # **red LED still behaving as if set to invert power config**
00:02:30 | [D] | [switch:012] | 'Kauf Plug' Turning ON.
00:02:30 | [D] | [switch:066] | 'Kauf Plug': Sending state ON
00:02:30 | [D] | [switch:066] | 'Kauf Plug Red LED': Sending state OFF
00:02:30 | [D] | [script:077] | Script 'script_save_changes' restarting (mode: restart)
00:02:33 | [D] | [esp8266.preferences:274] | Saving preferences to flash...

</body>
</html>

**Comment by bkaufx** [comment]
Thanks for letting me know.  I just pushed out a fix for the yaml package if you compile it yourself.  I'll put out a precompiled binary in the next day or two to fix it.

**Comment by Grafton1046** [comment]
@bkaufx Thanks for the speedy reply, you've just added another reason I'm happy with the bulbs and smart plugs in my house! Just realized I submitted this on the PLF10 repository instead of the PLF12.
