### ISSUE TITLE
Changing firmware to Tasmota

### ISSUE THREAD

**Issue by freedomlives** [KaufHA/PLF10#2]
Hi,
I bought the plugs on Amazon. First poweron, I connect to the built in webserver, upload tasmota.bin, click Update, and then I just get "connection timed out". I've tried also tasmota.bin.gz and tried from my laptop (Firefox) or Android phone. Neither seem to work.
Is there some other way to upload Tasmota firmware? (If it really comes to it, I have the serial cable, but was hoping to avoid that)

**Comment by freedomlives** [comment]
Now I tried Chromium on the laptop, and regardless whether the gzipped or not firmware, I get error "Update Failed: ERROR[4]: Not Enough Space"

**Comment by KaufHA** [comment]
Have you tried removing power to the plug and then powering it back on?  I think once there is a failed flash that space in flash that was occupied by the failed firmware upload doesn't necessarily free back up until the ESP reboots.

**Comment by freedomlives** [comment]
@KaufHA that solved the problem! Thanks!

**Comment by freedomlives** [comment]
For anyone running into this problem of not enough space-- for some reason, the second plug just didn't want to update with tasmota.bin.gz, so there is another file tasmota-lite.bin.gz and this one worked. Then I did an OTA upgrade to tasmota.bin.gz inside Tasmota.
