### ISSUE TITLE
Is there a python module for controlling/monitoring the PLF10?

### ISSUE THREAD

**Issue by DP-M** [KaufHA/PLF10#22]
Is there a python module I can use to control (ON/OFF), and get current/voltage/etc stats information from the KAUF PL10 with factory/default firmware? I'd like to use these in a completely standalone application without HASS, ESPHOME, etc.

**Comment by KaufHA** [comment]
Take a look at this, I think it should work.

https://github.com/esphome/aioesphomeapi

**Comment by DP-M** [comment]
Thanks for the reply. Unfortunately it's too far beyond my skillset. I was hoping for a simple module where I could import it, plug my device IP address in, and start turning things off/on and getting a status in a couple lines of code. I'm not familiar enough with ESPhome to figure out what features are implemented on these devices and how to use them. I appreciate the response though.

**Comment by KaufHA** [comment]
You can use the http/rest api through curl commands. I think this can be
used from Python pretty easily

https://github.com/KaufHA/common#http-api

**Comment by DP-M** [comment]
Yeah, that was my next option. I was hoping there was some module I wasn't able to find so that I wouldn't have to take care of my own error handling, etc. Thanks again for the quick response!
