### ISSUE TITLE
Locked myself out of Kauf Plug 10

### ISSUE THREAD

**Issue by UKnau22** [KaufHA/PLF10#23]
It seems it's asking for a password, but I don't know it.

Is there a way to fix this?

[logs_tv-plug_run.txt](https://github.com/KaufHA/PLF10/files/12411027/logs_tv-plug_run.txt)

**Comment by UKnau22** [comment]
It's not connecting through the web interface even though it shows online in ESPhome

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by bkaufx** [comment]
Can you try to upload bin file through curl command? curl -v -X POST -H "Content-Type: multipart/form-data" -F update=@firmware_filename.bin.gz  "http://192.168.1.16/update"

**Comment by UKnau22** [comment]
Is that in PowerShell or from Raspberry Pi?

In PowerShell I get this error:

PS C:\Users\Udo-Laptop\Downloads> curl -v -X POST -H "Content-Type: multipart/form-data" -F ***@***.*** "http://192.168.1.16/update"

Invoke-WebRequest : Cannot bind parameter 'Headers'. Cannot convert the

"Content-Type: multipart/form-data" value of type "System.String" to type

"System.Collections.IDictionary".

At line:1 char:20

+ curl -v -X POST -H "Content-Type: multipart/form-data" -F ***@***.*** ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : InvalidArgument: (:) [Invoke-WebRequest], Paramet

erBindingException

+ FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShe

ll.Commands.InvokeWebRequestCommand

Sent from [Mail](https://go.microsoft.com/fwlink/?LinkId=550986) for Windows

**Comment by bkaufx** [comment]
Probably needs to be a linux shell.  not sure how you would do this through powershell.  You could use the windows subsystem for linux or do it from a pi probably.

**Comment by UKnau22** [comment]
From my raspberry the command seems to work, but it’s refusing the connection. Just like when I try to connect to the webserver directly

***@***.***:/srv/dev-disk-by-uuid-d324f578-1271-4c7f-a5e0-ea2ad966ca11/Udo# curl -v -X POST -H "Content-Type: multipart/form-data" -F ***@***.*** "http://192.168.1.116/update"

Note: Unnecessary use of -X or --request, POST is already inferred.

* Trying 192.168.1.116:80...

* connect to 192.168.1.116 port 80 failed: Connection refused

* Failed to connect to 192.168.1.116 port 80: Connection refused

* Closing connection 0

curl: (7) Failed to connect to 192.168.1.116 port 80: Connection refused

Sent from [Mail](https://go.microsoft.com/fwlink/?LinkId=550986) for Windows

**Comment by bkaufx** [comment]
What does your yaml look like?  Did you do anything other than keep it at the default?  How did you lose the OTA password?

**Comment by UKnau22** [comment]
I didn’t know there was a OTA password. Never saved it anywhere…

The other KaufPlugs I have don’t seem to have it anywhere…

Here’s the yaml:

substitutions:

name: "tv-plug"

packages:

kauf.plf10: github://KaufHA/PLF10/kauf-plug.yaml

esphome:

name: ${name}

name_add_mac_suffix: false

api:

encryption:

key: LJ6CoBwKtyvWKFaSIcSwGjJR+WqAtQN9d5MXKGxDJmI=

wifi:

ssid: !secret wifi_ssid

password: !secret wifi_password

use_address: 192.168.1.116

Sent from [Mail](https://go.microsoft.com/fwlink/?LinkId=550986) for Windows

**Comment by bkaufx** [comment]
Did you actually flash the plug in the first place or has it never been flashed by you?  Might be a return that Amazon sold again instead of shipping back to me.

**Comment by bkaufx** [comment]
Another thing to try would be hold the button down for 30+ seconds to clear the wifi network.  The plug should put it's wifi ap back up so you can connect directly to the plug.  From there, you can try flashing the bin.gz file through the web interface (IP address 192.168.4.1) or using curl.

**Comment by UKnau22** [comment]
Never flashed this one.

I’m setting up a 4th spare one and that one’s working as expected so far

OK, I’ll try to do the 30 second button push. While it’s plugged in, correct?

Sent from [Mail](https://go.microsoft.com/fwlink/?LinkId=550986) for Windows

**Comment by UKnau22** [comment]
I think this plug is actually dead. There’s no light when I plug it in and the relay doesn’t click when I push the button..

Sent from [Mail](https://go.microsoft.com/fwlink/?LinkId=550986) for Windows

**Comment by bkaufx** [comment]
email me brian@kaufha.com and I'll send a replacement.
