### ISSUE TITLE
Flashed PLF10 with wrong firmware. How do I recover?

### ISSUE THREAD

**Issue by neillbell** [KaufHA/PLF10#27]
Due to an error while modifying the YAML of another device (D1 Mini Pro), I ended up flashing my PLF10 with the wrong firmware. When I got that straightened out, I got an error with a missing OTA password, but I was able to copy the password from the other device.
Now, when I try to install via ESPHOME, I get the following error:

``ERROR Error binary size: Error: ESP has been flashed with wrong flash size. Please choose the correct 'board' option (esp01_1m always works) and then flash over USB.``

I can still access the device via HTTP, so I tried that and got:

``Update Failed: ERROR[8]: Flash config wrong real: 1048576 IDE: 16777216``

Is there any way to recover from this?

**Comment by bkaufx** [comment]
I think you might be SOL then.  Once it is flashed with a 4M firmware image, then I think the flash is partitioned with OTA partitions that are now outside the bounds of where the flash memory actually exists so there is no way to ever upload an OTA image.  I'm not totally sure this is true, so you might try to get help on esp8266-specific or maybe general ESPHome forums.

Maybe try creating a bin file as small as possible.

Using just the following as the yaml config and then gzipping got me down to 216k.  Long shot but something to try.  Also try cutting power to the plug so the esp8266 completely turns off and back on.

```
esphome:
  name: adsf
  friendly_name: adsf

esp8266:
  board: esp01_1m

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

**Comment by neillbell** [comment]
I got tired of messing with it and gave up. I just ordered a new one. At least they are cheap!
Thanks for your help.
