### ISSUE TITLE
Failed to load packages. kauf-plug-lite.yaml does not exist in repository.

### ISSUE THREAD

**Issue by Pro75357** [KaufHA/PLF10#30]
Cannot update devices in ESPHome since recently. It seems the kauf-plug-lite.yaml has been removed from the repo?

**Comment by bkaufx** [comment]
I moved it into the config subdirectory so try adding that to the packages line.

```
packages:
  kauf.plf10: github://KaufHA/PLF10/config/kauf-plug-lite.yaml
```

**Comment by Pro75357** [comment]
That worked - thank you!
