### ISSUE TITLE
KAUF Plug Not Connecting or Responding

### ISSUE THREAD

**Issue by chadisrad323** [KaufHA/PLF10#7]
Hello:

I have about a dozen KAUF plugs and most are working fine. I have two that have been unplugged for a few weeks, and they were previously working fine connecting to my wifi, showing up in ESPHome, and usable within Home Assistant. However, I just plugged them in and they are not responding. They are not connecting to my wifi now. In the troubleshooting, it says to hold the button for 5 seconds so it will rebroadcast the AP, but this does not work. I also see that if it is connected to the network, you can go to the IP address and reset wifi, however, this also does not work because it's not connecting to my wifi. The light on the plug flashes a pale blue light for a fraction of a second, and it repeats every few seconds. Without it resetting and without connecting to my wifi, I'm unsure how to use these again.

Thanks,
Chad

**Comment by KaufHA** [comment]
That's pretty weird.  Is the button doing anything if you just press it?  Kind of sounds like a bad flash but that makes no sense if you didn't just flash it when it stopped working.  Email me brian@kaufha.com for replacements.

**Comment by chadisrad323** [comment]
Thanks for the reply. I will contact you at the email provided. I agree it's strange -- they were working perfectly last time they were plugged in. Pressing the button doesn't do anything at all.
